apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-awscli-app
  namespace: argocd
spec:
  project: default
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  sources:
  - chart: helm-s3-awscli-app-chart
    repoURL: 352858358668.dkr.ecr.us-east-1.amazonaws.com
    targetRevision: 0.0.1
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: https://github.com/candonov/helm-charts.git
    targetRevision: HEAD
    ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
