apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-irsa-app
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: https://github.com/candonov/helm-charts.git
    path: s3-irsa-app/
    targetRevision: HEAD
    helm:
      valueFiles:
      - $values/argocd/values.yaml
  - repoURL: https://github.com/candonov/helm-charts.git
    targetRevision: HEAD
    ref: values
  syncPolicy: {}
