apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "s3-irsa-app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "s3-irsa-app.name" . }}
    helm.sh/chart: {{ include "s3-irsa-app.chart" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "s3-irsa-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "s3-irsa-app.name" . }}
    spec:
      serviceAccountName: {{ include "s3-irsa-app.name" . }}
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do aws s3 ls; sleep 120; done"]
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "64Mi"
            cpu: "250m"
      restartPolicy: Always
