apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app.name" . }}
  labels:
    app.kubernetes.io/name: {{ include "demo-app.name" . }}
    helm.sh/chart: {{ include "demo-app.chart" . }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "demo-app.name" . }}

